# Generated by Django 3.1 on 2020-08-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pulldown',
            field=models.CharField(choices=[('0', '1,000'), ('2', '2,000'), ('3', '3,000'), ('4', '4,000')], default='', max_length=100, null='', verbose_name='no'),
        ),
    ]
