# Generated by Django 5.1.7 on 2025-03-13 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionWhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgment', models.CharField(max_length=50, unique=True)),
                ('phone_action', models.CharField(max_length=255)),
                ('edi_action', models.CharField(max_length=255)),
                ('record_action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evalution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=10)),
                ('alert_text', models.TextField()),
                ('retailer', models.CharField(max_length=255)),
                ('wholesaler', models.CharField(max_length=255)),
                ('day_of_week', models.CharField(max_length=10)),
                ('judgment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error')], max_length=10)),
                ('retailer', models.CharField(max_length=255)),
                ('wholesaler', models.CharField(max_length=255)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10)),
                ('alert_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('CharField', 'Character Field'), ('TextField', 'Text Field'), ('IntegerField', 'Integer Field'), ('BooleanField', 'Boolean Field'), ('DateField', 'Date Field'), ('DateTimeField', 'DateTime Field')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('choices', models.TextField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='automation.schema')),
            ],
        ),
    ]
