# Generated by Django 5.1.7 on 2025-03-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'decision',
            },
        ),
        migrations.RemoveField(
            model_name='evalution',
            name='alert_text',
        ),
        migrations.RemoveField(
            model_name='evalution',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='evalution',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='evalution',
            name='judgment',
        ),
        migrations.RemoveField(
            model_name='evalution',
            name='retailer',
        ),
        migrations.RemoveField(
            model_name='evalution',
            name='wholesaler',
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'Character Field'), ('TextField', 'Text Field')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='evalution',
            table='evalution',
        ),
    ]
