# Generated by Django 5.1.7 on 2025-03-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_decision_remove_evalution_alert_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='choices',
            field=models.TextField(blank=True, help_text='カンマ区切りで選択肢を入力', null=True),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'Character Field'), ('TextField', 'Text Field'), ('IntegerField', 'Integer Field'), ('BooleanField', 'Boolean Field'), ('ChoiceField', 'Choice Field')], max_length=50),
        ),
    ]
