# Generated by Django 5.1.7 on 2025-03-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_alter_schemafield_choices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('field_type', models.CharField(choices=[('CharField', '文字列'), ('TextField', 'テキスト'), ('IntegerField', '整数'), ('BooleanField', '真偽値'), ('ChoiceField', '選択肢')], default='CharField', max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.TextField(blank=True, help_text='ChoiceFieldの場合、カンマ区切りで選択肢を入力してください。', null=True)),
            ],
            options={
                'verbose_name': 'Recognitionフィールド',
                'verbose_name_plural': 'Recognitionフィールド',
                'db_table': 'recognition_field',
            },
        ),
        migrations.DeleteModel(
            name='DecisionWhat',
        ),
        migrations.DeleteModel(
            name='Recognition',
        ),
        migrations.AddField(
            model_name='decision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-15 10:06:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decision',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evalution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-15 10:06:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evalution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
