# Generated by Django 5.1.7 on 2025-03-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_recognitionfield_delete_decisionwhat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecognitionField',
            new_name='Recognition',
        ),
    ]
