# Generated by Django 5.1.7 on 2025-03-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_rename_recognitionfield_recognition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recognition',
            options={'verbose_name': 'Recognition', 'verbose_name_plural': 'Recognition'},
        ),
        migrations.AlterModelTable(
            name='recognition',
            table='Recognition',
        ),
    ]
