# Generated by Django 5.1.7 on 2025-03-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_alter_recognition_options_alter_recognition_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evalution',
            table='Evalution',
        ),
    ]
