# Generated by Django 5.1.7 on 2025-03-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_alter_evalution_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evalution',
            table='evalution',
        ),
    ]
