# Generated by Django 5.1.7 on 2025-03-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_alter_evalution_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decision',
        ),
        migrations.DeleteModel(
            name='Evalution',
        ),
        migrations.DeleteModel(
            name='Recognition',
        ),
    ]
