# Generated by Django 5.1.7 on 2025-03-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_delete_decision_delete_evaluation_delete_recognition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchemaField',
            new_name='SchemaFields',
        ),
    ]
