# Generated by Django 5.1.7 on 2025-04-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_rename_schemafield_schemafields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('wholesaler', 'Wholesaler')], max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
